name: Change Url

on:
  workflow_dispatch:
    inputs:
      url:
        description: Neue Url
        required: true
        
permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./addMusic
        run: npm install
      
      - name: change url in env file 
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "home:\"[a-zA-Z0-9]*\""
          replace: "home:\"${{ github.event.inputs.url }}\""
          regex: true
          
      - name: show contents
        working-directory: ./addMusic/src/environments
        run: cat environment.prod.ts 

      - name: Build
        working-directory: ./addMusic
        run: npm run build      

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addMusic.zip addMusic/dist/addMusic/

      - name: list dir
        run: ls
        
#      - name: Release angular
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: false
#          prerelease: false
#          release_name: 'test'
#          tag_name: 'v0.0.2'
#          files: addMusic.zip

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        working-directory: ./server
        run: mvn -B package --file pom.xml

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r backend.zip server/target/quarkus-app/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          release_name: 'test'
          tag_name: 'v0.0.3'
          files: |
            addMusic.zip
            backend.zip
            server/artists.csv
